set -g status-style 'bg=#f0f0f0 fg=#555555'
set -g window-status-current-style 'fg=#3366aa bold'
set -g window-status-style 'fg=#999999'
set -g pane-border-style 'fg=#cccccc bg=#fdfdfd'
set -g pane-active-border-style 'fg=#88aadd bg=#fdfdfd'
set -g message-style 'bg=#e8e8e8 fg=#333333'
set -g window-style 'bg=#fdfdfd fg=#555555'
set -g window-active-style 'bg=#fdfdfd fg=#333333'
